---

- name: install mysql
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="#bind-address = 127.0.0.1" state=present backrefs=yes backup=yes
  notify: mysql_restart

- name: remove test database
  mysql_db: name=test state=absent

- name: create databases
  mysql_db: name={{ item.name }} state=present
  with_items: mysql_db

- name: create database users
  mysql_user: name={{ item.name }}
              password={{ item.pass|default(item.name) }}
              priv={{ item.priv|default("*.*:ALL") }}
              state=present
              host={{ item.host | default("localhost") }}
  with_items: mysql_users

