---

- name: make production_databases directory
  file: path=/home/vagrant/production_databases state=directory group=vagrant owner=vagrant mode=0700

- name: put load_database.sh
  template: src=load_database.sh dest=/home/vagrant/load_database.sh group=vagrant owner=vagrant mode=0755

- name: put sync_database.sh
  template: src=sync_database.sh dest=/home/vagrant/sync_database.sh group=vagrant owner=vagrant mode=0755
