---

- name: install PHP
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - php-apc
    - php5
    - php5-cli
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-xdebug

