<?php IF(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php ELSE: ?>
    <!-- display the 'display name' of the user -->
    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>



<?php
// module/BasicInfo/view/basicInfo/basicInfo/edit.phtml:

$title = "Edit $sectionName section";
$this->headTitle($title);
?>
<style type="text/css">
textarea{
	width: 700px;
}
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div style="border-top:3px solid black;padding-bottom:20px;"></div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'section',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo '<div style="height:300px;">';
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('shop_id'));
echo $this->formHidden($form->get('type'));

echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('flag'));
echo $this->formRow($form->get('content'));
echo '</div>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<?php ENDIF ?>
