---

- name: install capistrano
  gem: name=capistrano version=3.3.5 state=present

- name: create configration for production deployment
  template: src=production.rb dest=/var/www/{{ host }}/config/deploy/production.rb group=dialout owner=501 mode=0644
