<?php IF(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php ELSE: ?>
    <!-- display the 'display name' of the user -->
    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>



<?php
// module/Rates/view/rates/rates/add.phtml:

$title = 'Add new rates';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br>
<div id="rates_cat_add">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('ratescat', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);

echo '<div class="input_area">';
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('shop_id'));
echo $this->formRow($form->get('name'));
echo "<div id='condition_show'>";
echo "</div>";

echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('ratescat',
        array('action'=>'index',));?>"><input type = "button" value = "Cancel" /></a>
<?php
echo $this->form()->closeTag();
?>
</div>
<?php ENDIF ?>
