<?php
$shop_info = null;
foreach ($basic_info as $single_info) {
    $shop_info = $single_info;
}
$shop_name = $shop_info->name;
$shop_address = $shop_info->address;
$shop_phone = $shop_info->phone;
$shop_email = $shop_info->email;
//	$shop_latitude = $shop_info->lattitude;
//	$shop_longitude = $shop_info->longitude;
?>

<!DOCTYPE html>

<html>
    <head>
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--meta-->
        <title><?php echo $shop_name; ?> - Contact Us - Sydney | Massage | Brothel | Escort | Adult Service | Best Sex | Top Hot Girls in Sydney</title>
        <meta charset="utf-8">
        <meta name="keywords"
              content="Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <meta name="description"
              content="Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <link rel="shortcut icon" href="/images/favicon.ico">
        <link rel="stylesheet" type="text/css" href="/frontend/css/main_front.css">

        <!--jquery-->
        <script src="/frontend/plugins/jquery/jquery-1.7.2.min.js"></script>

        <!--jquery ui-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"/>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>

        <!--jquery blockui-->
        <script src="/frontend/plugins/blockui/blockui.js"></script>

        <!--jscrollpane-->
        <link rel="stylesheet" href="/frontend/plugins/jscrollpane/css/jscrollpane.css"/>
        <script src="/frontend/plugins/jscrollpane/js/jscrollpane.js"></script>
        <script src="/frontend/plugins/jscrollpane/js/mousewheel.js"></script>

        <!-- Sticky Kit -->
        <script src="/frontend/plugins/Sticky-Kit/Sticky-Kit.js"></script>

        <!--google map-->
        <script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript"></script>
        <script type="text/javascript">
            var geocoder;
            var map;
            var address;
            var fenway = new google.maps.LatLng(0, 0);

            function initialize() {
                geocoder = new google.maps.Geocoder();
                var mapOptions = {
                    center: fenway,
                    zoom: 16,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                map = new google.maps.Map(document.getElementById("new_google_map_2"), mapOptions);

                var panoramaOptions = {
                    position: fenway,
                    pov: {
                        heading: 90,
                        pitch: 1,
                        zoom: 3
                    }
                };
                var panorama = new google.maps.StreetViewPanorama(document.getElementById("new_google_map_1"), panoramaOptions);
                map.setStreetView(panorama);
            }

            function codeAddress() {
                address = '<?php echo $shop_address; ?>';
                geocoder.geocode({'address': address}, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        map.setCenter(results[0].geometry.location);
                        var marker = new google.maps.Marker({
                            map: map,
                            position: results[0].geometry.location
                        });

                        createStreetMap('new_google_map_1', results[0].geometry.location);
                    } else {

                    }
                });
            }

            function createStreetMap(strMapCanvasID, yourLatLng) {
                var panorama;

                //once the document is loaded, see if google has a streetview image within 50 meters of the given location, and load that panorama
                var sv = new google.maps.StreetViewService();

                sv.getPanoramaByLocation(yourLatLng, 50, function (data, status) {
                    if (status == 'OK') {
                        //google has a streetview image for this location, so attach it to the streetview div
                        var panoramaOptions = {
                            pano: data.location.pano,
                            addressControl: false,
                            navigationControl: true,
                            navigationControlOptions: {
                                style: google.maps.NavigationControlStyle.SMALL
                            }
                        };
                        var panorama = new google.maps.StreetViewPanorama(document.getElementById(strMapCanvasID), panoramaOptions);


                        // lets try and hide the pegman control from the normal map, if we're displaying a seperate streetview map
                        objCreatedMap.setOptions({
                            streetViewControl: false
                        });
                    }
                    else {
                        //no google streetview image for this location, so hide the streetview div
                        $('#' + strMapCanvasID).parent().hide();
                    }
                });
            }

            $(function () {
                initialize();
                codeAddress();
            });
        </script>

        <script>
            $(function () {
                // top girl move
                window.setTimeout(function () {
                    $("div.div_top_girl").show("bounce", 500, function () {
                        $(this).animate({
                            "right": "885px",
                        }, 1000, function () {
                            $(this).hide().show("pulsate", 1000, function () {
                                $("div.div_top_title").show("clip", 1000, function () {
                                    $("div.div_desire_phone").show("drop", 1500);
                                });
                            });
                        });
                    });
                }, 1000);

                // 鼠标放在一个navi item上面
                $("div.navi_item:not(.navi_highlighted)").hover(function () {
                    $(this).addClass("navi_highlighted");
                }, function () {
                    $(this).removeClass("navi_highlighted");
                });

                // sticky menu
                $("div#navi_bar").stick_in_parent()
                    .on("sticky_kit:stick", function (e) {
                        $(this).css('margin-top', '0px'); // 根据需求修改
                    })
                    .on("sticky_kit:unstick", function (e) {
                        $(this).css('margin-top', '0px');
                    });

                // jscrollpane
                $("div.club8_text_content_contactus").jScrollPane();

                // 箭头的点击效果
                $(":submit#submit_input")
                    .mousedown(function () {
                        $(this).css("top", "2px").css("left", "1px");
                    })
                    .mouseup(function () {
                        $(this).css("top", "0px").css("left", "0px");
                    });

                // 发送邮件
                $(":submit#submit_input").click(function (e) {
                    e.preventDefault();

                    var customer_name = $.trim($(":text[name=customer_name]").val());
                    var customer_number = $.trim($(":text[name=customer_number]").val());
                    var customer_email = $.trim($(":text[name=customer_email]").val());
                    var customer_message = $.trim($(":input[name=customer_message]").val());

                    // 只有当customer_message为空时才禁止提交
                    if (customer_message == "") {
                        $("h3", $("div.growlUI")).text("Your message for us?");
                        $("h4", $("div.growlUI")).text("Thx heaps!");
                        $("div.growlUI").css("background", "url(/frontend/images/cross_2.png) no-repeat 10px 10px");

                        $.blockUI({
                            message: $("div.growlUI"),
                            fadeIn: 700,
                            fadeOut: 700,
                            timeout: 3000,
                            showOverlay: false,
                            centerY: false,
                            css: {
                                width: 'auto',
                                top: '',
                                left: '10px',
                                right: '',
                                bottom: '10px',
                                border: 'none',
                                padding: '5px',
                                backgroundColor: 'rgba(255, 255, 255, 0.8)',
                                //	'-webkit-border-radius': '10px',
                                //	'-moz-border-radius': '10px',
                                '-webkit-box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                                '-moz-box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                                'box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                                opacity: .8,
                                color: '#fff'
                            }
                        });
                        return false;
                    }

                    $.blockUI({
                        message: $("div.email_waiting"),
                        css: {
                            width: '450',
                            height: '70px',
                            border: 'none',
                            padding: '15px',
                            backgroundColor: 'rgba(178, 34, 34, 0.8)',
                            //	'-webkit-border-radius': '10px',
                            //	'-moz-border-radius': '10px',
                            '-webkit-box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                            '-moz-box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                            'box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                            opacity: .8,
                            color: '#fff'
                        }
                    });

                    $.post("/sex/ajaxmail",
                        {
                            "customer_name": customer_name,
                            "customer_number": customer_number,
                            "customer_email": customer_email,
                            "customer_message": customer_message
                        },
                        function (data) {
                            $("h3", $("div.growlUI")).text("Nicely done!");
                            $("h4", $("div.growlUI")).text("Message was sent successfully!");
                            $("div.growlUI").css("background", "url(/frontend/images/check_2.png) no-repeat 10px 10px");

                            $(":text[name=customer_name]").val("Enter your name.").addClass("gray_text");
                            $(":text[name=customer_number]").val("Enter your number.").addClass("gray_text");
                            $(":text[name=customer_email]").val("Enter your email.").addClass("gray_text");
                            $(":input[name=customer_message]").val("");

                            $.blockUI({
                                message: $("div.growlUI"),
                                fadeIn: 700,
                                fadeOut: 700,
                                timeout: 3000,
                                showOverlay: false,
                                centerY: false,
                                css: {
                                    width: 'auto',
                                    top: '',
                                    left: '10px',
                                    right: '',
                                    bottom: '10px',
                                    border: 'none',
                                    padding: '5px',
                                    backgroundColor: 'rgba(255, 255, 255, 0.8)',
                                    //	'-webkit-border-radius': '10px',
                                    //	'-moz-border-radius': '10px',
                                    '-webkit-box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                                    '-moz-box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                                    'box-shadow': '1px 1px 10px rgba(0, 0, 0, 0.5)',
                                    opacity: .8,
                                    color: '#fff'
                                }
                            });
                        },
                        'json'
                    );
                });
            });
        </script>

        <!-- form text -->
        <style>
            .gray_text {
                color: rgba(255, 255, 255, 1.0) !important;
            }
        </style>
        <script>
            $(function () {
                $(":text#customer_name")
                    .focus(function () {
                        if ($(this).val() == "Enter your name." && $(this).hasClass("gray_text")) {
                            $(this)
                                .removeClass("gray_text")
                                .val("");
                        }
                    })
                    .blur(function () {
                        if (!$(this).val()) {
                            $(this)
                                .val("Enter your name.")
                                .addClass("gray_text");
                        } else if ($(this).val() == "Enter your name.") {
                            $(this).addClass("gray_text");
                        }
                    });

                $(":text#customer_number")
                    .focus(function () {
                        if ($(this).val() == "Enter your number." && $(this).hasClass("gray_text")) {
                            $(this)
                                .removeClass("gray_text")
                                .val("");
                        }
                    })
                    .blur(function () {
                        if (!$(this).val()) {
                            $(this)
                                .val("Enter your number.")
                                .addClass("gray_text");
                        } else if ($(this).val() == "Enter your number.") {
                            $(this).addClass("gray_text");
                        }
                    });

                $(":text#customer_email")
                    .focus(function () {
                        if ($(this).val() == "Enter your email." && $(this).hasClass("gray_text")) {
                            $(this)
                                .removeClass("gray_text")
                                .val("");
                        }
                    })
                    .blur(function () {
                        if (!$(this).val()) {
                            $(this)
                                .val("Enter your email.")
                                .addClass("gray_text");
                        } else if ($(this).val() == "Enter your email.") {
                            $(this).addClass("gray_text");
                        }
                    });
            });
        </script>

        <!-- addthis -->
        <style>
            div.addthis_toolbox {
                display: none;
                right: 10px;
                top: 20px;
            }

            /*
            .addthis_floating_style{
                padding: 7px 5px;
                background: rgba(255, 255, 255, 0.6);

                border-radius: 5px;
                -moz-border-radius: 5px;
                -webkit-border-radius: 5px;

                -webkit-box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
                -moz-box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
                box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
            }

            a.addthis_button_compact{
                margin-bottom: 0px !important;
            }

            a.addthis_button_compact span{
                margin-bottom: 0px !important;
            }
            */
        </style>

        <script>
            jQuery(document).ready(function ($) {
                window.setTimeout(function () {
                    $("div.addthis_toolbox").fadeIn(1000);
                }, 2000);
            });
        </script>
    </head>

    <body>
        <h1 style="display: none;">Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h1>

        <h2 style="display: none;">Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h2>

        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_floating_style addthis_32x32_style" style="z-index: 10000;">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_pinterest_share"></a>
            <a class="addthis_button_google_plusone_share"></a>
        </div>
        <script type="text/javascript">var addthis_config = {"data_track_addressbar": true};</script>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51db41ce52c5a749"></script>
        <!-- AddThis Button END -->

        <!--growlUI-->
        <div class="growlUI" style="display: none;">
            <h3></h3>
            <h4></h4>
        </div>

        <!--Please wait...-->
        <div class="email_waiting" style="display: none;">
            <div class="loading">
                <img src="/frontend/images/loading_4.gif"/>
            </div>
            <div class="please_wait">
                We are sending your message.<br/>Please be patient...
            </div>
        </div>

        <div id="background">
            <div class="top_info">
                <div class="div_top_title font-effect-3d-float">
                    <a href="/sex/aboutus">
                        &nbsp;<?php echo $shop_name; ?>&nbsp;
                    </a>
                </div>
                <div class="div_top_girl">
                    <img src="/frontend/images/girl_top.png"/>
                </div>
                <div class="div_desire_phone">
                    <?php echo $shop_phone; ?>
                    <br/>
                    <?php echo $shop_address; ?>&nbsp;
                </div>
            </div>

            <div id="navi_bar">
                <div id="navi_bar_detail">
                    <a href="<?php echo $this->url('frontend', array('action' => 'aboutus')); ?>">
                        <div class="navi_item">
                            <div>About Us</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'gallery')); ?>">
                        <div class="navi_item">
                            <div>Ladies</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'timetable')); ?>">
                        <div class="navi_item">
                            <div>Timetable</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'prices')); ?>">
                        <div class="navi_item">
                            <div>Services</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'contactus')); ?>">
                        <div class="navi_item navi_highlighted">
                            <div>Contact Us</div>
                        </div>
                    </a>
                </div>
            </div>

            <!--RotatingImageSlider-->
            <link rel="stylesheet" type="text/css" href="/frontend/plugins/RotatingImageSlider/css/style.css"/>
            <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'/>
            <!--	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>-->
            <script type="text/javascript"
                    src="/frontend/plugins/RotatingImageSlider/js/jquery.transform-0.9.3.min_.js"></script>
            <script type="text/javascript" src="/frontend/plugins/RotatingImageSlider/js/jquery.mousewheel.js"></script>
            <script type="text/javascript" src="/frontend/plugins/RotatingImageSlider/js/jquery.RotateImageMenu.js"></script>
            <div id="rotating_slider">
                <div class="rm_wrapper">
                    <div id="rm_container" class="rm_container">
                        <ul>
                            <li data-images="rm_container_1" data-rotation="-10"><img src="/frontend/images/rotating/5/1.jpg"/>
                            </li>
                            <li data-images="rm_container_2" data-rotation="-5"><img src="/frontend/images/rotating/5/2.jpg"/>
                            </li>
                            <li data-images="rm_container_3" data-rotation="2"><img src="/frontend/images/rotating/5/3.jpg"/>
                            </li>
                            <li data-images="rm_container_4" data-rotation="9"><img src="/frontend/images/rotating/5/4.jpg"/>
                            </li>
                        </ul>
                        <div id="rm_mask_left" class="rm_mask_left"></div>
                        <div id="rm_mask_right" class="rm_mask_right"></div>
                        <div id="rm_corner_left" class="rm_corner_left"></div>
                        <div id="rm_corner_right" class="rm_corner_right"></div>
                        <!--
                        <h2>Fashion Explosion 2012</h2>
                        -->
                        <div style="display:none;">
                            <div id="rm_container_1">
                                <img src="/frontend/images/rotating/5/1.jpg"/>
                                <img src="/frontend/images/rotating/6/1.jpg"/>
                                <img src="/frontend/images/rotating/1/1.jpg"/>
                                <img src="/frontend/images/rotating/2/1.jpg"/>
                                <img src="/frontend/images/rotating/3/1.jpg"/>
                                <img src="/frontend/images/rotating/4/1.jpg"/>
                            </div>
                            <div id="rm_container_2">
                                <img src="/frontend/images/rotating/5/2.jpg"/>
                                <img src="/frontend/images/rotating/6/2.jpg"/>
                                <img src="/frontend/images/rotating/1/2.jpg"/>
                                <img src="/frontend/images/rotating/2/2.jpg"/>
                                <img src="/frontend/images/rotating/3/2.jpg"/>
                                <img src="/frontend/images/rotating/4/2.jpg"/>
                            </div>
                            <div id="rm_container_3">
                                <img src="/frontend/images/rotating/5/3.jpg"/>
                                <img src="/frontend/images/rotating/6/3.jpg"/>
                                <img src="/frontend/images/rotating/1/3.jpg"/>
                                <img src="/frontend/images/rotating/2/3.jpg"/>
                                <img src="/frontend/images/rotating/3/3.jpg"/>
                                <img src="/frontend/images/rotating/4/3.jpg"/>
                            </div>
                            <div id="rm_container_4">
                                <img src="/frontend/images/rotating/5/4.jpg"/>
                                <img src="/frontend/images/rotating/6/4.jpg"/>
                                <img src="/frontend/images/rotating/1/4.jpg"/>
                                <img src="/frontend/images/rotating/2/4.jpg"/>
                                <img src="/frontend/images/rotating/3/4.jpg"/>
                                <img src="/frontend/images/rotating/4/4.jpg"/>
                            </div>
                        </div>
                    </div>
                    <div class="rm_nav">
                        <a id="rm_next" href="#" class="rm_next"></a>
                        <a id="rm_prev" href="#" class="rm_prev"></a>
                    </div>
                    <div class="rm_controls">
                        <a id="rm_pause" href="#" class="rm_pause">Pause</a>
                        <a id="rm_play" href="#" class="rm_play">Play</a>
                    </div>
                </div>
            </div>

            <div id="container">
                <div class="background_opacity">
                    <div id="left_content_contact">
                        <div class="contact_left_left">
                            <div id="new_google_map_1">
                            </div>
                        </div>
                        <div class="contact_left_right">
                            <div id="new_contact_text">
                                <div class="club8_text_content_contactus">
                                    <?php echo stripslashes($contactus_text->content); ?>
                                </div>
                            </div>
                            <div id="new_google_map_2">
                            </div>
                        </div>
                    </div>

                    <div class="divider_v_15">
                    </div>

                    <div id="right_content_contact">
                        <div id="new_contact_right_container">
                            <div id="new_contact_info">
                                <div class="new_info">
                                    <div class="new_info_key">Phn.</div>
                                    <div class="new_info_value"><?php echo $shop_phone; ?></div>
                                </div>
                                <div class="new_info">
                                    <div class="new_info_key">Eml.</div>
                                    <div class="new_info_value"><?php echo $shop_email; ?></div>
                                </div>
                                <div class="new_info">
                                    <div class="new_info_key">Add.</div>
                                    <div class="new_info_value"><?php echo $shop_address; ?></div>
                                </div>
                            </div>

                            <div class="divider_h">
                            </div>

                            <div id="form_div">
                                <form>
                                    <div id="div_text">
                                        <input type="text" name="customer_name" id="customer_name" class="gray_text"
                                               value="Enter your name."/>
                                        <input type="text" name="customer_number" id="customer_number" class="gray_text"
                                               value="Enter your number."/>
                                        <input type="text" name="customer_email" id="customer_email" class="gray_text"
                                               value="Enter your email."/>
                                        <textarea name="customer_message" id="customer_message"></textarea>
                                    </div>
                                    <div id="div_submit">
                                        <input type="submit" id="submit_input" value=">>"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer_own">
                Copyright &copy; 2009-2015 <?php echo $shop_name; ?>, All Rights Reserved.
            </div>
        </div>
    </body>
</html>