<?php include_once('common/top.phtml'); ?>

<!DOCTYPE html>

<html>
    <head>
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--meta-->
        <title><?php echo $shop_name; ?> - Ladies - Sydney | Massage | Brothel | Escort | Adult Service | Best Sex | Top Hot Girls in Sydney</title>
        <meta charset="utf-8">
        <meta name="keywords"
              content="Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <meta name="description"
              content="Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <link rel="shortcut icon" href="/images/favicon.ico">
        <link rel="stylesheet" type="text/css" href="/frontend/css/main_front.css">

        <!--fonts-->
        <link href='http://fonts.googleapis.com/css?family=Bilbo+Swash+Caps' rel='stylesheet' type='text/css'>
        <!-- girl name -->

        <!--jquery-->
        <script src="/frontend/plugins/jquery/jquery-1.7.2.min.js"></script>

        <!--jquery ui-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"/>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>

        <!--jquery lightbox-->
        <link rel="stylesheet" href="/frontend/plugins/lightbox/css/lightbox.css"/>
        <script src="/frontend/plugins/lightbox/js/lightbox.js"></script>

        <!--jquery blockui-->
        <script src="/frontend/plugins/blockui/blockui.js"></script>

        <!--crawler-->
        <script type="text/javascript" src="/frontend/plugins/crawler/crawler.js"></script>

        <!--jCapSlide-->
        <link rel="stylesheet" type="text/css" href="/frontend/plugins/jCapSlide/jquery.capSlide.css" media="screen"/>
        <script src="/frontend/plugins/jCapSlide/jquery.capSlide.js" type="text/javascript"></script>

        <!--Mosaic-->
        <link rel="stylesheet" href="/frontend/plugins/Mosaic/css/mosaic.css" type="text/css" media="screen"/>
        <script type="text/javascript" src="/frontend/plugins/Mosaic/js/mosaic.1.0.1.js"></script>

        <!-- Sticky Kit -->
        <script src="/frontend/plugins/Sticky-Kit/Sticky-Kit.js"></script>

        <script>
            $(function () {
                // sticky menu
                $("div#navi_bar").stick_in_parent()
                    .on("sticky_kit:stick", function (e) {
                        $(this).css('margin-top', '0px'); // 根据需求修改
                    })
                    .on("sticky_kit:unstick", function (e) {
                        $(this).css('margin-top', '0px');
                    });

                // top girl move
                window.setTimeout(function () {
                    $("div.div_top_girl").show("bounce", 500, function () {
                        $(this).animate({
                            "right": "885px",
                        }, 1000, function () {
                            $(this).hide().show("pulsate", 1000, function () {
                                $("div.div_top_title").show("clip", 1000, function () {
                                    $("div.div_desire_phone").show("drop", 1500);
                                });
                            });
                        });
                    });
                }, 1000);

                // 鼠标放在一个navi item上面
                $("div.navi_item:not(.navi_highlighted)").hover(function () {
                    $(this).addClass("navi_highlighted");
                }, function () {
                    $(this).removeClass("navi_highlighted");
                });

                // sticky menu
                //	$("div#navi_bar").stickyit();
            });
        </script>

        <!-- addthis -->
        <style>
            div.addthis_toolbox {
                display: none;
                right: 10px;
                top: 20px;
            }

            /*
            .addthis_floating_style{
                padding: 7px 5px;
                background: rgba(255, 255, 255, 0.6);

                border-radius: 5px;
                -moz-border-radius: 5px;
                -webkit-border-radius: 5px;

                -webkit-box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
                -moz-box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
                box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
            }

            a.addthis_button_compact{
                margin-bottom: 0px !important;
            }

            a.addthis_button_compact span{
                margin-bottom: 0px !important;
            }
            */
        </style>
        <script>
            jQuery(document).ready(function ($) {
                window.setTimeout(function () {
                    $("div.addthis_toolbox").fadeIn(1000);
                }, 2000);
            });
        </script>
        <!-- end of addthis -->

        <!-- girl marquee -->
        <?php
        $first_girl = reset($girl_photo_array);
        ?>
        <script>
            $(function () {
                var girl_id_now = <?php echo $first_girl['girl_id']; ?>;
                var girl_click_locked = false;

                var num_girl_block = parseInt($("div.girl_block").length) - 1;

                //	create_girl();
                //	hide_none_girl();

                marqueeInit({
                    uniqueid: 'mycrawler',
                    style: {
                        'padding': '0px',
                    },
                    inc: 6,
                    mouse: 'cursor driven',
                    moveatleast: 2,
                    neutral: 150,
                    noAddedSpace: true,
                    //	noAddedAlt: true,
                    //	random: true,
                    savedirection: true,
                    initcontent: function (contentarray) {
                        $("div.loading_gallery").hide();

                        // 新的chrome在crawler有问题，需要指定一个系列的宽度
                        $(contentarray[0]).css("width", (num_girl_block * 155) + "px");
                        $(contentarray[1]).css("width", (num_girl_block * 155) + "px");

                        $(contentarray[0]).find("img.new_girl_img").each(function () {
                            var $marquee_image = $(this);
                            girl_click($marquee_image);
                        });

                        $(contentarray[1]).find("img.new_girl_img").each(function () {
                            var $marquee_image = $(this);
                            girl_click($marquee_image);
                        });
                    }
                });

                function girl_click($image) {
                    // display big pictures
                    $image.click(function () {
                        if (girl_click_locked) {
                            return;
                        }
                        girl_click_locked = true;

                        var girl_id = $(this).attr("girl_id");
                        $("div.new_girl_right[girl_id=" + girl_id_now + "]").hide("slide", 400, function () {
                            $("div.new_girl_right[girl_id=" + girl_id + "]").show("slide", 400, function () {
                                girl_id_now = girl_id;
                                girl_click_locked = false;
                            });
                        });
                        //	girl_id_now = $(this).attr("girl_id");
                        //	hidden_comments_obj = $("div.hidden_comments[girl_id=" + girl_id_now + "]");
                        //	$("div.scroll_pane").jScrollPane();
                    });
                }
            });

            function create_girl() {
                var girl_num = <?php echo count($girl_photo_array); ?>;
                var block_num = Math.ceil(girl_num / 2);

                for (var i = 0; i < block_num; i++) {
                    var $girl_block = $("div#girl_block_sample").clone();
                    $girl_block.show();
                    $girl_block.attr("id", i.toString());
                    $("div#mycrawler").append($girl_block);
                }

                var j = 2;
                <?php foreach($girl_photo_array as $girl): ?>
                $("img.new_girl_img").eq(j)
                    .attr("src", "<?php echo $girl['girl_thumb']; ?>")
                    .attr("girl_id", "<?php echo $girl['girl_id']; ?>");

                $("div.new_girl_div").eq(j).show();

                j++;
                <?php endforeach; ?>
            }

            function hide_none_girl() {
                $("img.new_girl_img").each(function () {
                    if ($.trim($(this).attr("src")) == "sample") {
                        $(this).parent().hide();
                    }
                });
            }
        </script>

        <!-- girl detail -->
        <script>
            $(function () {
                // 刷新显示第一个girl
                $("div.new_girl_right[girl_id=<?php echo $first_girl['girl_id']; ?>]").show();

                // 点击小图显示大图及信息
                setTimeout(function () {

                }, 200);

                // Mosaic
                $(".mosaic-block").mosaic({
                    animation: 'slide',	//fade or slide
                    speed: '400',
                    hover_x: '229px',	//Horizontal position on hover
                    hover_y: '324px'
                });
            });
        </script>
    </head>

    <body>
        <img style="display: none;" src="/frontend/images/loading_4.gif"/>

        <h1 style="display: none;">Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h1>

        <h2 style="display: none;">Sydney, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Nylons, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h2>

        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_floating_style addthis_32x32_style" style="z-index: 10000;">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_pinterest_share"></a>
            <a class="addthis_button_google_plusone_share"></a>
        </div>
        <script type="text/javascript">var addthis_config = {"data_track_addressbar": true};</script>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51db41ce52c5a749"></script>
        <!-- AddThis Button END -->

        <div id="background">
            <div class="top_info">
                <div class="div_top_title font-effect-3d-float">
                    <a href="/sex/aboutus">
                        &nbsp;<?php echo $shop_name; ?>&nbsp;
                    </a>
                </div>
                <div class="div_top_girl">
                    <img src="/frontend/images/girl_top.png"/>
                </div>
                <div class="div_desire_phone">
                    <?php echo $shop_phone; ?>
                    <br/>
                    <?php echo $shop_address; ?>&nbsp;
                </div>
            </div>

            <div id="navi_bar">
                <div id="navi_bar_detail">
                    <a href="<?php echo $this->url('frontend', array('action' => 'aboutus')); ?>">
                        <div class="navi_item">
                            <div>About Us</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'gallery')); ?>">
                        <div class="navi_item navi_highlighted">
                            <div>Ladies</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'timetable')); ?>">
                        <div class="navi_item">
                            <div>Timetable</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'prices')); ?>">
                        <div class="navi_item">
                            <div>Services</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'contactus')); ?>">
                        <div class="navi_item">
                            <div>Contact Us</div>
                        </div>
                    </a>
                </div>
            </div>

            <!--RotatingImageSlider-->
            <link rel="stylesheet" type="text/css" href="/frontend/plugins/RotatingImageSlider/css/style.css"/>
            <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'/>
            <script type="text/javascript"
                    src="/frontend/plugins/RotatingImageSlider/js/jquery.transform-0.9.3.min_.js"></script>
            <script type="text/javascript" src="/frontend/plugins/RotatingImageSlider/js/jquery.mousewheel.js"></script>
            <script type="text/javascript"
                    src="/frontend/plugins/RotatingImageSlider/js/jquery.RotateImageMenu.js"></script>
            <div id="rotating_slider">
                <div class="rm_wrapper">
                    <div id="rm_container" class="rm_container">
                        <ul>
                            <li data-images="rm_container_1" data-rotation="-10"><img
                                    src="/frontend/images/rotating/2/1.jpg"/></li>
                            <li data-images="rm_container_2" data-rotation="-5"><img
                                    src="/frontend/images/rotating/2/2.jpg"/></li>
                            <li data-images="rm_container_3" data-rotation="2"><img
                                    src="/frontend/images/rotating/2/3.jpg"/></li>
                            <li data-images="rm_container_4" data-rotation="9"><img
                                    src="/frontend/images/rotating/2/4.jpg"/></li>
                        </ul>
                        <div id="rm_mask_left" class="rm_mask_left"></div>
                        <div id="rm_mask_right" class="rm_mask_right"></div>
                        <div id="rm_corner_left" class="rm_corner_left"></div>
                        <div id="rm_corner_right" class="rm_corner_right"></div>
                        <!--
                        <h2>Fashion Explosion 2012</h2>
                        -->
                        <div style="display:none;">
                            <div id="rm_container_1">
                                <img src="/frontend/images/rotating/2/1.jpg"/>
                                <img src="/frontend/images/rotating/3/1.jpg"/>
                                <img src="/frontend/images/rotating/4/1.jpg"/>
                                <img src="/frontend/images/rotating/5/1.jpg"/>
                                <img src="/frontend/images/rotating/6/1.jpg"/>
                                <img src="/frontend/images/rotating/1/1.jpg"/>
                            </div>
                            <div id="rm_container_2">
                                <img src="/frontend/images/rotating/2/2.jpg"/>
                                <img src="/frontend/images/rotating/3/2.jpg"/>
                                <img src="/frontend/images/rotating/4/2.jpg"/>
                                <img src="/frontend/images/rotating/5/2.jpg"/>
                                <img src="/frontend/images/rotating/6/2.jpg"/>
                                <img src="/frontend/images/rotating/1/2.jpg"/>
                            </div>
                            <div id="rm_container_3">
                                <img src="/frontend/images/rotating/2/3.jpg"/>
                                <img src="/frontend/images/rotating/3/3.jpg"/>
                                <img src="/frontend/images/rotating/4/3.jpg"/>
                                <img src="/frontend/images/rotating/5/3.jpg"/>
                                <img src="/frontend/images/rotating/6/3.jpg"/>
                                <img src="/frontend/images/rotating/1/3.jpg"/>
                            </div>
                            <div id="rm_container_4">
                                <img src="/frontend/images/rotating/2/4.jpg"/>
                                <img src="/frontend/images/rotating/3/4.jpg"/>
                                <img src="/frontend/images/rotating/4/4.jpg"/>
                                <img src="/frontend/images/rotating/5/4.jpg"/>
                                <img src="/frontend/images/rotating/6/4.jpg"/>
                                <img src="/frontend/images/rotating/1/4.jpg"/>
                            </div>
                        </div>
                    </div>
                    <div class="rm_nav">
                        <a id="rm_next" href="#" class="rm_next"></a>
                        <a id="rm_prev" href="#" class="rm_prev"></a>
                    </div>
                    <div class="rm_controls">
                        <a id="rm_pause" href="#" class="rm_pause">Pause</a>
                        <a id="rm_play" href="#" class="rm_play">Play</a>
                    </div>
                </div>
            </div>

            <div id="container">
                <div class="background_opacity">
                    <!------------------------------------- 左边girl滚动 ------------------------------------>
                    <!------------------------------------- 左边girl滚动 ------------------------------------>
                    <!------------------------------------- 左边girl滚动 ------------------------------------>
                    <!------------------------------------- 左边girl滚动 ------------------------------------>
                    <!------------------------------------- 左边girl滚动 ------------------------------------>
                    <div class="new_girl_left">
                        <div class="loading_gallery">
                            <img src="/frontend/images/loading_4.gif"/>
                        </div>

                        <div class="marquee" id="mycrawler">
                            <div class="girl_block" id="girl_block_sample">
                                <div class="new_girl_div">
                                    <img girl_id="1" class="new_girl_img" src="sample"/>
                                </div>
                                <div class="new_girl_div new_girl_div_2">
                                    <img girl_id="2" class="new_girl_img" src="sample"/>
                                </div>
                            </div>
                        </div>
                        <script>
                            create_girl();
                            hide_none_girl();
                        </script>
                    </div>

                    <div class="divider_v_15">
                    </div>

                    <!------------------------------------- 右边girl细节 ------------------------------------>
                    <!------------------------------------- 右边girl细节 ------------------------------------>
                    <!------------------------------------- 右边girl细节 ------------------------------------>
                    <!------------------------------------- 右边girl细节 ------------------------------------>
                    <!------------------------------------- 右边girl细节 ------------------------------------>
                    <?php foreach ($girl_photo_array as $girl): ?>
                        <div class="new_girl_right" girl_id="<?php echo $girl['girl_id']; ?>">
                            <div class="new_girl_detail_img">
                                <a href="<?php echo $girl['girl_photos']['first']->pict_url; ?>"
                                   rel="lightbox[<?php echo $girl['girl_id']; ?>]">
                                    <div class="mosaic-block">
                                        <div class="mosaic-overlay">
                                            <?php if ($girl['girl_is_new']): ?>
                                                <div class="new_star">
                                                    <?php echo $girl['girl_star_text']; ?>
                                                </div>
                                            <?php endif; ?>
                                            <img src="<?php echo $girl['girl_thumb']; ?>"/>
                                        </div>
                                        <div class="mosaic-backdrop">
                                            <div class="details">
                                                <div class="detail_age">
                                                    <div class="detail_key">AGE:</div>
                                                    <div class="detail_value"><?php echo $girl['girl_age']; ?></div>
                                                </div>
                                                <div class="detail_from">
                                                    <div class="detail_key">FROM:</div>
                                                    <div class="detail_value"><?php echo $girl['girl_nationality']; ?></div>
                                                </div>

                                                <div class="clearfix"></div>

                                                <div class="detail_desc">
                                                    <div class="detail_key">ABOUT ME:</div>
                                                    <div class="detail_value"><?php echo $girl['girl_description']; ?></div>
                                                </div>
                                                <div class="detail_roster">
                                                    <div class="detail_key">TIMETABLE:</div>
                                                    <div class="detail_value">
                                                        <?php
                                                        $i = 1;
                                                        foreach ($girl["girl_roster"] as $is_on) {
                                                            if ($is_on) {
                                                                echo "<div class = 'girl_roster_div girl_roster_active'>";
                                                            } else {
                                                                echo "<div class = 'girl_roster_div'>";
                                                            }

                                                            switch ($i++) {
                                                                case 1:
                                                                    echo "M";
                                                                    break;
                                                                case 2:
                                                                    echo "T";
                                                                    break;
                                                                case 3:
                                                                    echo "W";
                                                                    break;
                                                                case 4:
                                                                    echo "T";
                                                                    break;
                                                                case 5:
                                                                    echo "F";
                                                                    break;
                                                                case 6:
                                                                    echo "S";
                                                                    break;
                                                                case 7:
                                                                    echo "S";
                                                                    break;
                                                            }

                                                            echo "</div>";
                                                            //	echo "</div>"; // 不要删除
                                                        }
                                                        ?>
                                                    </div>
                                                </div>
                                                <div class="detail_photos">
                                                    <div class="detail_key">PHOTOS:</div>
                                                    <div class="detail_value">
                                                        <div>
                                                            <img src="<?php echo $girl['girl_thumb']; ?>"/>
                                                        </div>
                                                        <?php foreach ($girl['girl_photos']['others'] as $photo): ?>
                                                            <div>
                                                                <img src="<?php echo $photo->thumb_url; ?>"/>
                                                            </div>
                                                        <?php endforeach; ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                                <?php foreach ($girl['girl_photos']['others'] as $photo): ?>
                                    <a href="<?php echo $photo->pict_url; ?>"
                                       rel="lightbox[<?php echo $girl['girl_id']; ?>]"></a>
                                <?php endforeach; ?>
                            </div>
                            <div class="new_girl_detail_name">
                                <?php echo $girl['girl_name']; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="footer_own">
                Copyright &copy; 2009-2015 <?php echo $shop_name; ?>, All Rights Reserved.
            </div>
        </div>
        <?php include_once('common/bottom.phtml'); ?>
    </body>
</html>