<?php
$shop_info = null;
foreach ($basic_info as $single_info) {
    $shop_info = $single_info;
}
$shop_name = $shop_info->name;
$shop_address = $shop_info->address;
$shop_phone = $shop_info->phone;
$shop_email = $shop_info->email;
?>

<!DOCTYPE html>

<html>
    <head>
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--meta-->
        <title>Paddington 244 - Timetable - Sydney | Massage | Brothel | Escort | Adult Service | Best Sex | Top Hot Girls in
            Paddington Sydney</title>
        <meta charset="utf-8">
        <meta name="keywords"
              content="Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <meta name="description"
              content="Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <link rel="shortcut icon" href="/images/favicon.ico">
        <link rel="stylesheet" type="text/css" href="/frontend/css/main_front.css">

        <!--jquery--> <!-- 这个jquery是目前能兼容所有需求的版本 -->
        <script src="/frontend/plugins/jquery/jquery-1.7.2.min.js"></script>

        <!--jquery ui-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"/>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>

        <!--lightbox-->
        <script type="text/javascript" src="/frontend/plugins/lightbox_1/jquery.lightbox-0.5.pack.js"></script>
        <script type="text/javascript" src="/frontend/plugins/lightbox_1/jquery.idTabs.pack.js"></script>
        <link rel="stylesheet" type="text/css" href="/frontend/plugins/lightbox_1/jquery.lightbox-0.5.css" media="screen"/>

        <!--jscrollpane-->
        <link rel="stylesheet" href="/frontend/plugins/jscrollpane/css/jscrollpane.css"/>
        <script src="/frontend/plugins/jscrollpane/js/jscrollpane.js"></script>
        <script src="/frontend/plugins/jscrollpane/js/mousewheel.js"></script>

        <!-- Sticky Kit -->
        <script src="/frontend/plugins/Sticky-Kit/Sticky-Kit.js"></script>

        <script>
            $(function () {
                // top girl move
                window.setTimeout(function () {
                    $("div.div_top_girl").show("bounce", 500, function () {
                        $(this).animate({
                            "right": "885px",
                        }, 1000, function () {
                            $(this).hide().show("pulsate", 1000, function () {
                                $("div.div_top_title").show("clip", 1000, function () {
                                    $("div.div_desire_phone").show("drop", 1500);
                                });
                            });
                        });
                    });
                }, 1000);

                // 鼠标放在一个navi item上面
                $("div.navi_item:not(.navi_highlighted)").hover(function () {
                    $(this).addClass("navi_highlighted");
                }, function () {
                    $(this).removeClass("navi_highlighted");
                });

                // sticky menu
                $("div#navi_bar").stick_in_parent()
                    .on("sticky_kit:stick", function (e) {
                        $(this).css('margin-top', '0px'); // 根据需求修改
                    })
                    .on("sticky_kit:unstick", function (e) {
                        $(this).css('margin-top', '0px');
                    });

                // 鼠标放在roster表的tr上
                $("div.body_table_div").find("td").hover(
                    function () {
                        var index_td = $(this).index();

                        $(this).parent().find("td:gt(0)").css({
                            "opacity": "0.8",
                        });
                        if (index_td > 0) {
                            $("div.body_table_div").find("tr").each(function () {
                                $(this).find("td:gt(0)").eq(index_td - 1).css({
                                    "opacity": "0.8",
                                });
                            });
                        }
                    },
                    function () {
                        var index_td = $(this).index();

                        $(this).parent().find("td:gt(0)").each(function () {
                            if (!$(this).html()) {
                                $(this).css({
                                    "opacity": "0.5",
                                });
                            }
                        });

                        if (index_td > 0) {
                            $("div.body_table_div").find("tr").each(function () {
                                if (!$(this).find("td:gt(0)").eq(index_td - 1).html()) {
                                    $(this).find("td:gt(0)").eq(index_td - 1).css({
                                        "opacity": "0.5",
                                    });
                                }
                            });
                        }
                    }
                );

                <?php foreach($girl_array as $girl_info): ?>
                $('a[rel=<?php echo $girl_info["girl"]->id; ?>]').lightBox({
                    imageLoading: "/frontend/plugins/lightbox_1/images/loading.gif",
                    imageBtnClose: "/frontend/plugins/lightbox_1/images/close.gif",
                    imageBtnPrev: "/frontend/plugins/lightbox_1/images/prev.gif",
                    imageBtnNext: "/frontend/plugins/lightbox_1/images/next.gif",
                });
                <?php endforeach; ?>

                // jascrollpane
                $("div.body_table_div").jScrollPane();

                // Tooltips
                $(document).tooltip({
                    show: {
                        effect: "bounce",
                        delay: 100,
                    },
                    hide: {
                        effect: "drop",
                        delay: 100,
                    },
                    position: {
                        my: "center bottom-20",
                        at: "center top",
                        using: function (position, feedback) {
                            $(this).css(position);
                            $("<div>")
                                .addClass("arrow")
                                .addClass(feedback.vertical)
                                .addClass(feedback.horizontal)
                                .appendTo(this);
                        }
                    }
                });
            });
        </script>

        <!-- tooltips -->
        <style>
            .ui-tooltip, .arrow:after {
                background: #fff;
                border: 1px solid #fff;
            }

            .ui-tooltip {
                padding: 10px 20px;
                color: #b22222;
                border-radius: 20px;
                font: bold 16px "Helvetica Neue", Sans-Serif;
                /*	text-transform: uppercase;*/
                box-shadow: 0 0 7px #000;
            }

            .arrow {
                width: 70px;
                height: 16px;
                overflow: hidden;
                position: absolute;
                left: 50%;
                margin-left: -35px;
                bottom: -16px;
            }

            .arrow.top {
                top: -16px;
                bottom: auto;
            }

            .arrow.left {
                left: 20%;
            }

            .arrow:after {
                content: "";
                position: absolute;
                left: 20px;
                top: -20px;
                width: 25px;
                height: 25px;
                box-shadow: 6px 5px 9px -9px black;
                -webkit-transform: rotate(45deg);
                -moz-transform: rotate(45deg);
                -ms-transform: rotate(45deg);
                -o-transform: rotate(45deg);
                tranform: rotate(45deg);
            }

            .arrow.top:after {
                bottom: -20px;
                top: auto;
            }
        </style>

        <!-- scroll -->
        <style>
            div.jspDrag {

            }

            div.jspTrack {
                background-color: #fff;
                opacity: 0.8;
                filter: alpha(opacity=80);
            }

            div.jspVerticalBar {
                background: none;
            }
        </style>

        <!-- addthis -->
        <style>
            div.addthis_toolbox {
                display: none;
                right: 10px;
                top: 20px;
            }

            /*
            .addthis_floating_style{
                padding: 7px 5px;
                background: rgba(255, 255, 255, 0.6);

                border-radius: 5px;
                -moz-border-radius: 5px;
                -webkit-border-radius: 5px;

                -webkit-box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
                -moz-box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
                box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.5);
            }

            a.addthis_button_compact{
                margin-bottom: 0px !important;
            }

            a.addthis_button_compact span{
                margin-bottom: 0px !important;
            }
            */
        </style>

        <script>
            jQuery(document).ready(function ($) {
                window.setTimeout(function () {
                    $("div.addthis_toolbox").fadeIn(1000);
                }, 2000);
            });
        </script>
    </head>

    <body>
        <h1 style="display: none;">Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h1>

        <h2 style="display: none;">Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h2>

        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_floating_style addthis_32x32_style" style="z-index: 10000;">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_pinterest_share"></a>
            <a class="addthis_button_google_plusone_share"></a>
        </div>
        <script type="text/javascript">var addthis_config = {"data_track_addressbar": true};</script>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51db41ce52c5a749"></script>
        <!-- AddThis Button END -->

        <div id="background">
            <div class="top_info">
                <div class="div_top_title font-effect-3d-float">
                    <a href="/sex/aboutus">
                        &nbsp;Paddington 244&nbsp;
                    </a>
                </div>
                <div class="div_top_girl">
                    <img src="/frontend/images/girl_top.png"/>
                </div>
                <div class="div_desire_phone">
                    <?php echo $shop_phone; ?>
                    <br/>
                    <?php echo $shop_address; ?>&nbsp;
                </div>
            </div>

            <div id="navi_bar">
                <div id="navi_bar_detail">
                    <a href="<?php echo $this->url('frontend', array('action' => 'aboutus')); ?>">
                        <div class="navi_item">
                            <div>About Us</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'gallery')); ?>">
                        <div class="navi_item">
                            <div>Ladies</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'timetable')); ?>">
                        <div class="navi_item navi_highlighted">
                            <div>Timetable</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'prices')); ?>">
                        <div class="navi_item">
                            <div>Services</div>
                        </div>
                    </a>
                    <a href="<?php echo $this->url('frontend', array('action' => 'contactus')); ?>">
                        <div class="navi_item">
                            <div>Contact Us</div>
                        </div>
                    </a>
                </div>
            </div>

            <!--RotatingImageSlider-->
            <link rel="stylesheet" type="text/css" href="/frontend/plugins/RotatingImageSlider/css/style.css"/>
            <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'/>
            <!--	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>-->
            <script type="text/javascript"
                    src="/frontend/plugins/RotatingImageSlider/js/jquery.transform-0.9.3.min_.js"></script>
            <script type="text/javascript" src="/frontend/plugins/RotatingImageSlider/js/jquery.mousewheel.js"></script>
            <script type="text/javascript" src="/frontend/plugins/RotatingImageSlider/js/jquery.RotateImageMenu.js"></script>
            <div id="rotating_slider">
                <div class="rm_wrapper">
                    <div id="rm_container" class="rm_container">
                        <ul>
                            <li data-images="rm_container_1" data-rotation="-10"><img src="/frontend/images/rotating/3/1.jpg"/>
                            </li>
                            <li data-images="rm_container_2" data-rotation="-5"><img src="/frontend/images/rotating/3/2.jpg"/>
                            </li>
                            <li data-images="rm_container_3" data-rotation="2"><img src="/frontend/images/rotating/3/3.jpg"/>
                            </li>
                            <li data-images="rm_container_4" data-rotation="9"><img src="/frontend/images/rotating/3/4.jpg"/>
                            </li>
                        </ul>
                        <div id="rm_mask_left" class="rm_mask_left"></div>
                        <div id="rm_mask_right" class="rm_mask_right"></div>
                        <div id="rm_corner_left" class="rm_corner_left"></div>
                        <div id="rm_corner_right" class="rm_corner_right"></div>
                        <!--
                        <h2>Fashion Explosion 2012</h2>
                        -->
                        <div style="display:none;">
                            <div id="rm_container_1">
                                <img src="/frontend/images/rotating/3/1.jpg"/>
                                <img src="/frontend/images/rotating/4/1.jpg"/>
                                <img src="/frontend/images/rotating/5/1.jpg"/>
                                <img src="/frontend/images/rotating/6/1.jpg"/>
                                <img src="/frontend/images/rotating/1/1.jpg"/>
                                <img src="/frontend/images/rotating/2/1.jpg"/>
                            </div>
                            <div id="rm_container_2">
                                <img src="/frontend/images/rotating/3/2.jpg"/>
                                <img src="/frontend/images/rotating/4/2.jpg"/>
                                <img src="/frontend/images/rotating/5/2.jpg"/>
                                <img src="/frontend/images/rotating/6/2.jpg"/>
                                <img src="/frontend/images/rotating/1/2.jpg"/>
                                <img src="/frontend/images/rotating/2/2.jpg"/>
                            </div>
                            <div id="rm_container_3">
                                <img src="/frontend/images/rotating/3/3.jpg"/>
                                <img src="/frontend/images/rotating/4/3.jpg"/>
                                <img src="/frontend/images/rotating/5/3.jpg"/>
                                <img src="/frontend/images/rotating/6/3.jpg"/>
                                <img src="/frontend/images/rotating/1/3.jpg"/>
                                <img src="/frontend/images/rotating/2/3.jpg"/>
                            </div>
                            <div id="rm_container_4">
                                <img src="/frontend/images/rotating/3/4.jpg"/>
                                <img src="/frontend/images/rotating/4/4.jpg"/>
                                <img src="/frontend/images/rotating/5/4.jpg"/>
                                <img src="/frontend/images/rotating/6/4.jpg"/>
                                <img src="/frontend/images/rotating/1/4.jpg"/>
                                <img src="/frontend/images/rotating/2/4.jpg"/>
                            </div>
                        </div>
                    </div>
                    <div class="rm_nav">
                        <a id="rm_next" href="#" class="rm_next"></a>
                        <a id="rm_prev" href="#" class="rm_prev"></a>
                    </div>
                    <div class="rm_controls">
                        <a id="rm_pause" href="#" class="rm_pause">Pause</a>
                        <a id="rm_play" href="#" class="rm_play">Play</a>
                    </div>
                </div>
            </div>

            <div id="container">
                <div class="background_opacity">
                    <div class="new_roster_div">
                        <div class="head_table_div">
                            <table class="head_table">
                                <tr>
                                    <th>&nbsp;</th>
                                    <th>mon</th>
                                    <th>tue</th>
                                    <th>wed</th>
                                    <th>thur</th>
                                    <th>fri</th>
                                    <th>sat</th>
                                    <th>sun</th>
                                </tr>
                            </table>
                        </div>
                        <div class="body_table_div">
                            <table class="body_table">
                                <?php foreach ($girl_array as $girl_info): ?>
                                    <tr>
                                        <td>
                                            <a title="<?php echo $girl_info["girl"]->description; ?>"
                                               rel="<?php echo $girl_info["girl"]->id; ?>"
                                               href="<?php echo $girl_info["first_photo"]->pict_url; ?>">
                                                <?php echo $girl_info["girl"]->name; ?>
                                            </a>
                                            <?php foreach ($girl_info['other_photos'] as $photo): ?>
                                                <a title="<?php echo $girl_info["girl"]->description; ?>"
                                                   rel="<?php echo $girl_info["girl"]->id; ?>"
                                                   href="<?php echo $photo->pict_url; ?>"></a>
                                            <?php endforeach; ?>
                                        </td>

                                        <?php
                                        foreach ($girl_info["working_days"] as $is_on) {
                                            if ($is_on) {
                                                echo "<td style = 'opacity: 0.8; filter: alpha(opacity = 80);'><img src = '/frontend/images/kiss.png' /></td>";
                                            } else {
                                                echo "<td style = ''></td>";
                                            }
                                        }
                                        ?>
                                    </tr>
                                <?php endforeach; ?>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="footer_own">
                Copyright &copy; 2009-2013 Paddington 244, All Rights Reserved.
            </div>
        </div>
    </body>
</html>