<?php
$shop_info = null;
foreach ($basic_info as $single_info) {
    $shop_info = $single_info;
}
$shop_name = $shop_info->name;
$shop_address = $shop_info->address;
$shop_phone = $shop_info->phone;
$shop_email = $shop_info->email;
?>

<!DOCTYPE html>

<html>
    <head>
        <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!--meta-->
        <title>Paddington 244 - Warning - Sydney | Massage | Brothel | Escort | Adult Service | Best Sex | Top Hot Girls in
            Paddington Sydney</title>
        <meta charset="utf-8">
        <meta name="keywords"
              content="Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <meta name="description"
              content="Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝, 丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会">
        <link rel="shortcut icon" href="/images/favicon.ico">
        <link rel="stylesheet" type="text/css" href="/frontend/css/main_front.css">

        <!--fonts-->
        <link href='http://fonts.googleapis.com/css?family=Meie+Script' rel='stylesheet' type='text/css'>
        <!-- warning text -->

        <!--jquery-->
        <script src="/frontend/plugins/jquery/jquery-1.7.2.min.js"></script>

        <!--jquery ui-->
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"/>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>

        <!--camera-->
        <link rel='stylesheet' href='/frontend/plugins/Camera/css/camera.css'>
        <script src="/frontend/plugins/Camera/js/jquery.mobile.customized.min.js"></script>
        <script src="/frontend/plugins/Camera/js/jquery.easing.1.3.js"></script>
        <script src="/frontend/plugins/Camera/js/camera.min.js"></script>

        <!--typing text-->
        <script src="/frontend/plugins/typingText/TypingText.js"></script>

        <script>
            $(function () {
                // top girl move
                window.setTimeout(function () {
                    $("div.div_top_girl").show("bounce", 500, function () {
                        $(this).animate({
                            "right": "885px",
                        }, 1000, function () {
                            $(this).hide().show("pulsate", 1000, function () {
                                $("div.div_top_title").show("clip", 1000, function () {
                                    $("div.div_desire_phone").show("drop", 1500);
                                });
                            });
                        });
                    });
                }, 1000);

                // enjoy twinkling
                window.setInterval(function () {
                    $(".a_enjoy").hide().show("pulsate", 1000);
                }, 2000);

                // camera
                $('div#camera_wrap').camera({
                    height: '400px',
                    loader: 'bar',
                    pagination: false,
                    thumbnails: true,
                    time: 2500,
                    transPeriod: 1500,
                    loaderColor: '#000',
                    loaderBgColor: '#fff',
                    //	playPause: false
                });
            });
        </script>
    </head>

    <body>
        <h1 style="display: none;">Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h1>

        <h2 style="display: none;">Sydney, Paddington, Massage, Brothel, Escort, Adult Service, ML, Best Sex, Spa, Top Hot Asian
            Girls, Blow Job, Hand Job, Pantyhose, Tights, Fetish, 悉尼, 色情, 成人, 减压, 性爱, 性交, 口交, 肛交, 足交, 恋丝, 恋足, 推油, 丝袜, 黑丝, 肉丝,
            丝足, 制服, 女仆, 护士, 空姐, 巨乳, 美女, 亚洲, 打飞机, 出钟, 按摩, 妓院, 鸡店, 桑拿, 性服务, 会所, 夜总会</h2>

        <div id="background">
            <div class="top_info">
                <div class="div_top_title font-effect-3d-float">
                    &nbsp;Paddington 244&nbsp;
                </div>
                <div class="div_top_girl">
                    <img src="/frontend/images/girl_top.png"/>
                </div>
                <div class="div_desire_phone">
                    <?php echo $shop_phone; ?>
                    <br/>
                    <?php echo $shop_address; ?>&nbsp;
                </div>
            </div>

            <div class="warning_text">
                <div class="please_leave">
                    &nbsp;This website may be inappropriate for some viewers. Please <a class="a_leave"
                                                                                        href="http://www.google.com">leave</a>
                    if you are under 18 years of age, or come and <a class="a_enjoy" href="<?php echo $this->url('frontend',
                        array('action' => 'aboutus')); ?>">enjoy</a>!<br/><br/><span
                        style='margin-left: 670px;'>Paddington 244</span>
                </div>
            </div>

            <div class="warning_banner">
                <div class="camera_wrap camera_white_skin" id="camera_wrap"
                     style="height: 400px; background: url(/frontend/images/banner_11.jpg)">
                    <div data-thumb="/frontend/images/banner_11_tb.jpg" data-src="/frontend/images/banner_11.jpg"></div>
                    <div data-thumb="/frontend/images/banner_18_tb.jpg" data-src="/frontend/images/banner_18.jpg"></div>
                    <div data-thumb="/frontend/images/banner_22_tb.jpg" data-src="/frontend/images/banner_22.jpg"></div>
                    <div data-thumb="/frontend/images/banner_12_tb.jpg" data-src="/frontend/images/banner_12.jpg"></div>
                    <div data-thumb="/frontend/images/banner_13_tb.jpg" data-src="/frontend/images/banner_13.jpg"></div>
                    <div data-thumb="/frontend/images/banner_15_tb.jpg" data-src="/frontend/images/banner_15.jpg"></div>
                </div>
            </div>

            <div class="footer_own">
                Copyright &copy; 2009-2013 Paddington 244, All Rights Reserved.
            </div>
        </div>
    </body>
</html>