<?php IF(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php ELSE: ?>
    <!-- display the 'display name' of the user -->
    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>



<?php
// module/BasicInfo/view/section/section/index.phtml:

$title = 'Website Sections';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('section', array('action'=>'add'));?>">Add new section content</a>
</p>

<table class="table">
<tr>
    <th>name</th>
    <th>flag</th>
    <th>content</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($sections as $section) : ?>
<tr>
    <td><?php echo $this->escapeHtml($section->name);?></td>
    <td><?php echo $this->escapeHtml($section->flag);?></td>
    <td><?php echo $this->escapeHtml($section->content);?></td>
    <td>
        <a href="<?php echo $this->url('section',
            array('action'=>'edit', 'id' => $section->id));?>">Edit</a>
        <a href="<?php echo $this->url('section',
            array('action'=>'delete', 'id' => $section->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

<?php ENDIF ?>
