---

- name: copy private key
  copy: src=../.ssh/id_rsa dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=0400

- name: copy public key
  copy: src=../.ssh/id_rsa.pub dest=/home/vagrant/.ssh/id_rsa.pub owner=vagrant group=vagrant

- name: copy configuration file
  copy: src=../.ssh/config dest=/home/vagrant/.ssh/config owner=vagrant group=vagrant mode=0600
