---

- name: copy private key
  copy: src=../.ssh/id_rsa dest=/home/vagrant/.ssh/id_rsa group=vagrant owner=vagrant mode=0400

- name: copy public key
  copy: src=../.ssh/id_rsa.pub dest=/home/vagrant/.ssh/id_rsa.pub group=vagrant owner=vagrant mode=0644

- name: copy configuration file
  copy: src=../.ssh/config dest=/home/vagrant/.ssh/config group=vagrant owner=vagrant mode=0600
