---

- hosts: all
  sudo: yes
  roles:
    - system
    - ntp
    - ruby
    - php
    - composer
    - apache
    - mysql
    - phpmyadmin
    - ssh
    - git

  vars:
    host: light.erniuniu.com
    document_root: "/var/www/{{ host }}"
    dbname: erniuniu
    mysql_db:
      - name: "{{ dbname }}"
    mysql_users:
      - name: "{{ dbname }}"
        pass: "{{ dbname }}"
        priv: "{{ dbname }}.*:ALL"
        host: "%"
    git_user:
        email: yngwie.chang@gmail.com
        name: Hao Chang
