---

- hosts: all
  sudo: yes
  roles:
    - system
    - ntp
    - ruby
    - php
    - composer
    - apache
    - mysql
    - phpmyadmin
    - ssh
    - git
    - aws

  vars:
    host: light.erniuniu.com.local
    dbname: erniuniu
    mysql_root_password: root
    mysql_databases:
      - name: "{{ dbname }}"
    mysql_users:
      - name: "{{ dbname }}"
        pass: "{{ dbname }}"
        priv: "{{ dbname }}.*:ALL"
        host: "%"
    phpmyadmin_advanced_username: pma
    phpmyadmin_advanced_password: pmapass
    git_user:
        email: yngwie.chang@gmail.com
        name: Hao Chang

  vars_prompt:
    - name: "s3_user_key"
      prompt: "The Access Key ID for a AWS user with full S3 access"
      # private has to be yes here. There is a bug: https://github.com/mitchellh/vagrant/issues/2924
      private: yes
    - name: "s3_user_secret"
      prompt: "The Secret Access Key for the S3 user"
      private: yes
