<?php IF(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php ELSE: ?>
    <!-- display the 'display name' of the user -->
    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>



<?php
// module/Rates/view/rates/rates/add.phtml:

$title = "Add new rates of $ratesCat->name";
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br>
<!-- 这个加上之后页面里面的控件变得很大
<div id="rates_add">
-->
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('rates', array('action' => 'add','id' => $ratesCat->id,)));
$form->prepare();

echo $this->form()->openTag($form);

echo '<div class="input_area">';
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('shop_id'));
echo $this->formHidden($form->get('cat_id'));
echo $this->formRow($form->get('info'));
echo $this->formRow($form->get('price'));
echo "</div>";
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('ratescat',
        array('action'=>'index',));?>"><input type = "button" value = "Cancel" /></a>
<?php
echo $this->form()->closeTag();
?>
<!--
</div>
-->
<?php ENDIF ?>
