<?php IF(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php ELSE: ?>
    <!-- display the 'display name' of the user -->
    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>



<?php
// module/Rates/view/rates/rates/edit.phtml:

$title = 'Edit rates';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'rates',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('shop_id'));
echo $this->formHidden($form->get('cat_id'));
echo $this->formRow($form->get('info'));
echo $this->formRow($form->get('price'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('ratescat',
        array('action'=>'index',));?>"><input type = "button" value = "Cancel" /></a>
<?php

echo $this->form()->closeTag();
?>

<?php ENDIF ?>
