---

- name: install git
  apt: pkg=git state=latest update_cache=yes cache_valid_time=60

- name: set global user name
  shell: git config --global user.name "{{ git_user.name }}"
  sudo: no

- name: set global user email
  shell: git config --global user.email "{{ git_user.email }}"
  sudo: no

- name: set system user name
  shell: git config --system user.name "{{ git_user.name }}"

- name: set system user email
  shell: git config --system user.email "{{ git_user.email }}"
